### ISSUE TITLE
CLI klienta

### ISSUE THREAD

**Issue by Batory12** [DawidDebkowski/Trylma#8]
do przesyłania ruchów

**Comment by DawidDebkowski** [comment]
I. W trakcie gry:

1. Przyjmuje komendy:
Move i showboard
 a. Move - jeżeli jego ruch przyjmuje pozycję początkową i końcową 
b. showboard pokazuje aktualny stan planszy, który jest przechowywany lokalnie

2. Przyjmuje informacje od serwera:
a. O ruchu innego gracza -> zmienia stan planszy
b. O tym że teraz jego ruch -> pozwala wysłać move do serwera
c. O potwierdzeniu poprawności ruchu -> zmienia stan planszy / każe wysłać ruch jeszcze raz 
d. O zakończeniu gry 

Przed grą:
Pierwszy połączony gracz będzie "adminem"
1. Przyjmuje komendy 
a. ready -> oznacza gotowość do gry, gdy wszyscy są gotowi rozgrywka się zaczyna 
b. changePlayerCount -> zmienia ilość graczy, cofa status ready graczy

2. Informacje od serwera:
a. Gra się zaczęła 

Przed połączeniem
1. Komendy:
a. Połącz

2. Info od serwera
a. Czy połączenie się udało
